# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e5c23dcc01e9503d75bb50b90a8f0c46f65b805c6fc1c981cffc7a4ec3392eee128aaced7175b7077416b3d4fe94b8f0ea587ac0226cbe374485588df1f7f7

test:
  secret_key_base: a70d5e55078d8a98895555a0fc7b8aabccc8cd03cb81f5f8c0fc8105ff26a0e1aa1604a10d4f41fa299284a445daaa31bcd37514a8cccde8c3dfac6bc7d0ca16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
